### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by ANTEVETY** [PushkinStudio/PsRealVehicle#62]
Привет. У вас получился замечательный плагин! Как по моему не хватает полноценной демо сцены с уже настроенными колесными и гусеничными машинами. Так сразу и не разберешься. И вопрос не по этому плагину и который хочется задать именно вам. Открыл переменные для бп(подвеска, масса, rpm и т.п.) в PhysXVehicles, задача изменять их прямо в игре(не на ходу). После вставки значений переменных я для апдейта вызываю мою блупринтовую функцию в WheeledVehicleMovementComponent.cpp

void UWheeledVehicleMovementComponent::NewUpdatePhysicsState()
{
#if WITH_PHYSX
	FPhysXVehicleManager::VehicleSetupTag++;
#endif
}
, 
получается она дергает в PhysXVehicleManager.h(26). Всё в редакторе работает и применяется, но в уже собранной версии(win64) постоянный краш. Подсказки брал тут [https://answers.unrealengine.com/questions/284962/added-blueprintreadwrite-to-uproperty-but-property.html](url)  Я пока что в тупике...буду благодарен если подскажите куда копать, или может в вашем плагине можно параметры менять во время игры? В стандартном просто больше параметров именно для четырёхколесных, а это то что надо для меня.

**Comment by ufna** [comment]
@ANTEVETY , привет!

Т.к. вопрос не по PsRealVehicle, я issue закрываю :) Что касательно самого вопроса - я думаю, что ответы на ансверхабе за 2015 год не очень актуальны для текущих версий. Здесь нужно во-первых четко отследить краш, а после - уже раскапывать текущую интеграцию физикса на предмет нужного вам функционала. По этой теме я, увы, не подскажу.

**Comment by ANTEVETY** [comment]
Ок, спасибо, будем за вами следить)
