### ISSUE TITLE
Incorrect property

### ISSUE THREAD

**Issue by Yakim3396** [PushkinStudio/PsRealVehicle#68]
https://github.com/PushkinStudio/PsRealVehicle/blob/8bdcaa5c98e813f56bcdd55b4637806921fe41a7/Source/PsRealVehiclePlugin/Classes/PrvVehicleMovementComponent.h#L462

@ufna 

UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = Vehicle, meta = (DisplayName = "Override"))

**Comment by ufna** [comment]
Грац!
